### ISSUE TITLE
Invalid format '::endgroup::' Error after v2.1.0

### ISSUE THREAD

**Issue by MahmoudHaouachi2** [karancode/yamllint-github-action#13]
Today I ran my Github workflow and the yamllint action was throwing this error

`Error: Unable to process file command 'output' successfully.
Error: Invalid format '::endgroup::'`
 I rolled back to v2.0.0 and it worked again

**Comment by AnkurSinghalFlare** [comment]
Getting the same error

**Comment by ahoglund** [comment]
This is also affect our builds on https://github.com/github/rest-api-description. Will pin to v2.0.0 until this is addressed.

**Comment by saibrindavansonos** [comment]
Same with us.

**Comment by karancode** [comment]
thanks to @beiertu-mms, who added fix for this solution. Please try `@master` or [`@v2.1.1`](https://github.com/karancode/yamllint-github-action/releases/tag/v2.1.1). 🙇🏼 ❤️
