### ISSUE TITLE
PR comment behavior

### ISSUE THREAD

**Issue by steinbrueckri** [karancode/yamllint-github-action#4]
When "yamllint_comment" is set to false the action is still comment to the PR.

**Comment by karancode** [comment]
@steinbrueckri it's a known issue https://github.com/karancode/yamllint-github-action/issues/2. I will fix it asap.
PS : PRs are welcome 😇

**Comment by steinbrueckri** [comment]
Maybe I have same free time at the weekend to create an pullrequest. 😊

**Comment by steinbrueckri** [comment]
@karancode can you assign this issue to me I will take care now.

**Comment by steinbrueckri** [comment]
@karancode can you take a look at the open PR #5 ?

**Comment by karancode** [comment]
@steinbrueckri thank you again. I have added few comments. PTAL when you've time 😃
